name: genshinfan
description: "GenshinFan power by KanThin"
publish_to: "none"
version: 2.1.0

environment:
  sdk: ">=3.4.0-99.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  get:
  get_storage:

  dio: ^5.4.0
  connectivity_plus: ^5.0.2

  animate_do: ^3.3.3
  cached_network_image: ^3.3.1
  styled_text: ^8.1.0

  flutter_launcher_icons: ^0.13.1

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/ic_launcher_foreground.png"
  remove_alpha_ios: true
